package javadev.manish.service.orders;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-08-06T23:41:52.718+05:30
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://www.manish.javadev/service/Orders/", name = "Orders")
@XmlSeeAlso({com.javadev.manish.schema.order.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Orders {

    @WebResult(name = "orderInquiryResponse", targetNamespace = "http://www.manish.javadev.com/schema/Order", partName = "orderInquiryResponse")
    @WebMethod(operationName = "ProcessOrderPlacement", action = "http://www.manish.javadev/service/Orders/ProcessOrderPlacement")
    public com.javadev.manish.schema.order.OrderInquiryResponseType processOrderPlacement(
        @WebParam(partName = "orderInquiry", name = "orderInquiry", targetNamespace = "http://www.manish.javadev.com/schema/Order")
        com.javadev.manish.schema.order.OrderInquiryType orderInquiry
    );
}
